server:
    port: 8081
    error:
        whitelabel:
            enabled: false

keycloak:
    enabled: true
    realm: workshop
# Scenario A
    public-client: true

# Scenario B
#    credentials:
#        secret: 451c21ba-3869-4e79-b0cd-8ea2065f94ef

# Scenario C
#    bearer-only: true
    auth-server-url: http://127.0.0.1:8080/auth
    ssl-required: external
    resource: sample-app
    verify-token-audience: true
    use-resource-role-mappings: true
    confidential-port: 0
    securityConstraints:
    -   authRoles:
        - greeter
        securityCollections:
        -   name: greeter
            patterns:
            - /api/*